-- Run this once in the Supabase SQL Editor to set up the todos table.
-- Table: todos
-- Columns map 1:1 to the app's todo model (see ROADMAP.md, Phase 1).

create table if not exists public.todos (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
    text text not null,
    completed boolean not null default false,
    due_date date,
    priority text not null default 'low' check (priority in ('low', 'medium', 'high')),
    tags text[] not null default '{}',
    subtasks jsonb not null default '[]'::jsonb,
    notes text not null default '',
    position double precision not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists todos_user_id_idx on public.todos (user_id);

-- Row-Level Security: users can only see/modify their own todos.
alter table public.todos enable row level security;

drop policy if exists "Users manage their own todos" on public.todos;
create policy "Users manage their own todos"
    on public.todos
    for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- Keep updated_at current on every change.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end $$;

drop trigger if exists todos_set_updated_at on public.todos;
create trigger todos_set_updated_at
    before update on public.todos
    for each row execute function public.set_updated_at();

-- Enable realtime for the todos table (required for live sync between devices).
do $$
begin
    if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'todos'
    ) then
        alter publication supabase_realtime add table public.todos;
    end if;
end $$;